const $=id=>document.getElementById(id);let P=[],sel=-1,drag=null;
function size(){return $('ori').value==='portrait'?{w:210,h:297}:{w:297,h:210}}
function fname(){let a=($('doc').value||'A4-Photo-Studio').trim().replace(/[^\w-]+/g,'-'),b=($('nick').value||'Photos').trim().replace(/[^\w-]+/g,'-'),t=$('time').checked?'_'+new Date().toISOString().slice(0,16).replace('T','_').replace(':',''):'';return a+'_'+b+t+'.pdf'}
function preview(){$('preview').textContent=fname()} $('nick').oninput=$('doc').oninput=$('time').onchange=preview;
$('files').onchange=e=>[...e.target.files].forEach(f=>{let r=new FileReader();r.onload=()=>{let i=P.length;P.push({src:r.result,x:10+(i%2)*100,y:10+Math.floor(i/2)*80,w:90,h:70});sel=i;render()};r.readAsDataURL(f)});
$('ori').onchange=render;$('clear').onclick=()=>{P=[];sel=-1;render()};$('auto').onclick=()=>{let s=size(),n=P.length,cols=n<3?n:2,g=5,w=(s.w-(cols+1)*g)/cols,h=65;P.forEach((p,i)=>{p.x=g+(i%cols)*(w+g);p.y=g+Math.floor(i/cols)*(h+g);p.w=w;p.h=h});render()};
function render(){$('page').className='a4 '+$('ori').value;$('page').innerHTML='';$('hint').style.display=P.length?'none':'block';P.forEach((p,i)=>{let e=document.createElement('div');e.className='item '+(i===sel?'sel':'');e.style.cssText=`left:${p.x}mm;top:${p.y}mm;width:${p.w}mm;height:${p.h}mm`;e.innerHTML=`<span class=tag>${i+1}</span><img src="${p.src}"><span class=handle></span>`;e.onpointerdown=x=>start(x,i,false);e.querySelector('.handle').onpointerdown=x=>{x.stopPropagation();start(x,i,true)};$('page').appendChild(e)});$('none').hidden=sel>=0;$('ctrl').hidden=sel<0;if(sel>=0){['x','y','w','h'].forEach(k=>$(k).value=Math.round(P[sel][k]*10)/10)}}
function start(e,i,r){sel=i;drag={i,r,sx:e.clientX,sy:e.clientY,p:{...P[i]}};render()}
document.onpointermove=e=>{if(!drag)return;let p=P[drag.i],s=size(),dx=(e.clientX-drag.sx)/3.7795,dy=(e.clientY-drag.sy)/3.7795;if(drag.r){p.w=Math.max(10,drag.p.w+dx);p.h=Math.max(10,drag.p.h+dy)}else{p.x=Math.max(0,Math.min(s.w-p.w,drag.p.x+dx));p.y=Math.max(0,Math.min(s.h-p.h,drag.p.y+dy))}render()};document.onpointerup=()=>drag=null;
['x','y','w','h'].forEach(k=>$(k).oninput=()=>{if(sel>=0){P[sel][k]=+$(k).value;render()}});$('remove').onclick=()=>{if(sel>=0){P.splice(sel,1);sel=-1;render()}};
$('crop').onclick=()=>{if(sel>=0){$('modal').hidden=false;draw()}};$('close').onclick=()=>$('modal').hidden=true;$('apply').onclick=()=>$('modal').hidden=true;$('zoom').oninput=draw;
function draw(){let c=$('canvas'),q=c.getContext('2d'),im=new Image();im.onload=()=>{q.clearRect(0,0,c.width,c.height);let z=+$('zoom').value,s=Math.max(c.width/im.width,c.height/im.height)*z,w=im.width*s,h=im.height*s;q.drawImage(im,(c.width-w)/2,(c.height-h)/2,w,h)};im.src=P[sel].src}
$('ai').onclick=()=>alert('AI-ready extension points: Auto Crop, ID Photo detection, background removal, enhancement and smart layout can be connected to an AI API.');
$('save').onclick=()=>{if(!P.length)return alert('Add pictures first.');let {jsPDF}=window.jspdf,s=size(),pdf=new jsPDF({orientation:$('ori').value,unit:'mm',format:'a4',compress:true});P.forEach(p=>pdf.addImage(p.src,'JPEG',p.x,p.y,p.w,p.h,undefined,'FAST'));pdf.save(fname())};preview();render();